package com.productservice.exception;

public enum ErrorCode {
    PRODUCT_NOT_FOUND,
    PRODUCT_SKU_CONFLICT,
    CATEGORY_NOT_FOUND,
    CATEGORY_NAME_CONFLICT,
    INVENTORY_NOT_FOUND,
    INSUFFICIENT_STOCK,
    INVALID_RELEASE_QUANTITY,
    VALIDATION_ERROR,
    INTERNAL_ERROR
}
